# Generated by Django 4.2.20 on 2026-01-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("game_tag", models.CharField(db_index=True, max_length=7)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("horror", "Horror"),
                            ("fps", "FPS"),
                            ("basquete", "Basquete"),
                            ("soccer", "Soccer"),
                            ("open_world", "Open World"),
                            ("third_person", "Third Person"),
                            ("rpg", "RPG"),
                            ("adventure", "Adventure"),
                            ("futball", "Futball"),
                        ],
                        max_length=20,
                    ),
                ),
                ("publisher", models.CharField(db_index=True, max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image", models.ImageField(upload_to="games/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "catalog_game",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="games/")),
                ("is_cover", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.game",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_game_image",
            },
        ),
    ]
