# Generated by Django 4.2.20 on 2026-01-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gameimage",
            table=None,
        ),
    ]
